name: '❓ Question'
description: Use this template if you have questions about usage or the library
title: '[Question]: '
labels: ['question']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your question! ❓

        To provide better support, please fill out the following information.

  - type: textarea
    id: question
    attributes:
      label: Question
      description: Please provide details about your question
      placeholder: Explain what you want to know or what you are struggling with
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Background / Context
      description: Describe the background or what you want to achieve
      placeholder: What are you trying to build or what is your situation?
    validations:
      required: false

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If you have relevant code, please provide it
      placeholder: |
        ```javascript
        // Relevant code
        ```
    validations:
      required: false

  - type: input
    id: library-version
    attributes:
      label: Library Version
      description: Specify the version of the library you are using
      placeholder: 'e.g. 1.0.0'
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the documentation but could not find an answer
          required: true
        - label: I have searched existing Issues and Discussions but could not find a similar question
          required: true
