name: Documentation

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'package.json'
  workflow_dispatch:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') ||
      github.event_name == 'pull_request' ||
      github.event_name == 'workflow_dispatch'

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ 
            github.event_name == 'workflow_run' && 'main' ||
            github.event_name == 'workflow_dispatch' && github.ref ||
            github.head_ref 
          }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run docs

      - name: Setup Pages
        if: github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch'
        uses: actions/configure-pages@v4

      - name: Upload to GitHub Pages
        if: github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

      - name: Deploy to GitHub Pages
        if: github.event_name == 'workflow_run' || github.event_name == 'workflow_dispatch'
        id: deployment
        uses: actions/deploy-pages@v4